name: lighthouse
inputs:
  - name: site_url
    description: URL to run Lighthouse audit
    required: true

  - name: output_path
    description: Directory to save Lighthouse JSON
    required: false
    default: "public/lighthouse"
