[build]
  command = "gatsby clean && gatsby build"
  publish = "public"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Plugin custom untuk menyimpan JSON ke /public
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    site_url = "https://prasetyodev.netlify.app"
    output_path = "public/lighthouse"

[functions]
  directory = "netlify/functions"