[build]
  command = "gatsby clean && gatsby build"
  publish = "public"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Plugin bawaan Netlify Lighthouse
[[plugins]]
  #package = "@netlify/plugin-lighthouse"

# Plugin custom untuk menyimpan JSON ke /public
[[plugins]]
  package = "./netlify-plugins/lighthouse"

  [plugins.inputs.settings]
    #opsional: hanya running di production deploy
    output_path = "lighthouse-results" 

  [plugins.inputs]
    site_url = "https://prasetyodev.netlify.app"